<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
<testsuite name="MyProject.Tests" tests="3" time="0.288" timestamp="2014-12-18T14:34:32" failures="1" errors="0" skipped="1">
<properties>
<property name="environment" value="64-bit .NET 4.0.30319.18444 [collection-per-class, parallel]" />
<property name="test-framework" value="xUnit.net 2.0.0.2785" />
<property name="config-file" value="C:\Jenkins\jobs\my-project\workspace\MyProject\xunit\xunit.console.exe.Config" />
</properties>
<testcase classname="MyProject.Tests.SampleFact" name="FailedTest" time="0.014">
<failure><![CDATA[
MESSAGE:
Assert.True() Failure
+++++++++++++++++++
STACK TRACE:
at MyProject.Tests.SampleFact.FailedTest() in c:\Jenkins\jobs\my-project\workspace\MyProject\MyProject.Tests\SampleFact.cs:line 16]]></failure>
</testcase>
<testcase classname="MyProject.Tests.SampleFact" name="SuccessfulTest" time="0.010" />
<testcase classname="MyProject.Tests.SampleFact" name="SkippedTest" time="0.000">
<skipped message="On Purpose" />
</testcase>
</testsuite>
</testsuites>
